id: "912012"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@lt'
      variable: TX:EXECUTING_PARANOIA_LEVEL
      value: "1"
      transformations: []
actions: []
chain: []
tags: []
