id: "9003000"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:crs_exclusions_nextcloud|TX:crs_exclusions_nextcloud'
      value: "0"
      transformations:
        - t:none
actions: []
chain: []
tags: []
