id: "942380"
msg: SQL Injection Attack
severity: 25
phase: 2
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: (?:b(?:havingb ?(?:['"][^=]{1,10}['" ?[=<>]+|d{1,10} ?[=<>]+)|(?i:having)bs+(?:'[^=]{1,10}'|d{1,10})s*?[=<>])|existss(?:s(?:electS(?:if(?:null)?s(|concat|top)|ystems()|b(?i:having)bs+d{1,10}|'[^=]{1,10}'|sselect)|(?i:bexecutes{1,5}[w.$]{1,5}s{0,3})|(?i:bcreates+?table.{0,20}?()|(?i:blikeW*?charW*?()|(?i:select.*?case)|(?i:from.*?limit)|(?i:bexecute()|(?i:ordersby))
      transformations:
        - t:none
        - t:urlDecodeUni
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.sql_injection_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-sqli
    - OWASP_CRS
    - capec/1000/152/248/66
    - PCI/6.5.2
    - paranoia-level/2
