id: "9002540"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /wp-admin/user-new.php
      transformations:
        - t:none
actions: []
chain:
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: createuser
      conditions:
        - operator: '@streq'
          variable: ARGS:action
          value: createuser
          transformations:
            - t:none
      actions: []
      chain: []
      tags: []
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@eq'
          variable: '&ARGS:action'
          value: "1"
          transformations:
            - t:none
      actions:
        - type: ctl
          key: ruleRemoveTargetById
          value: 931130;ARGS:url
        - type: ctl
          key: ruleRemoveTargetByTag
          value: OWASP_CRS;ARGS:pass1
        - type: ctl
          key: ruleRemoveTargetByTag
          value: OWASP_CRS;ARGS:pass1-text
        - type: ctl
          key: ruleRemoveTargetByTag
          value: OWASP_CRS;ARGS:pass2
      chain: []
      tags: []
tags: []
