id: "944200"
msg: Magic bytes Detected
severity: 25
phase: 2
action: block
pre_filter_keyword: xacxedx00x05
conditions:
    - operator: '@rx'
      variable: ARGS|ARGS_NAMES|REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_BODY|REQUEST_HEADERS|XML:/*|XML://@*
      value: xacxedx00x05
      transformations: []
actions:
    - type: setvar
      key: tx.rce_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-java
    - platform-multi
    - attack-rce
    - OWASP_CRS
    - capec/1000/152/248
    - PCI/6.5.2
    - paranoia-level/2
