id: "9006420"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: /search/
conditions:
    - operator: '@rx'
      variable: REQUEST_URI
      value: /search/d+/$
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:q
chain: []
tags: []
