id: "9006160"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /inline-mod/
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:author_alert_reason
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:message
chain: []
tags: []
