id: "932130"
msg: 'Remote Command Execution: Unix Shell Expression Found'
severity: 25
phase: 2
action: block
pre_filter_keyword: '{'
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: (?:$(?:((?:(.*)|.*))|{.*})|[<>](.*))
      transformations:
        - t:none
        - t:urlDecodeUni
        - t:cmdLine
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.rce_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-shell
    - platform-unix
    - attack-rce
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/152/248/88
    - PCI/6.5.2
