id: "942330"
msg: Detects classic SQL injection probings 1/3
severity: 25
phase: 2
action: block
pre_filter_keyword: winformation_schema
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: (?i:(?:^(?:["'`\\]*?(?:[^"'`]+["'`]|[d"'`]+)s*?(?:n(?:and|ot)|(?:x?x)?or|between||||like|and|div|&&)s*?[w"'`][+&!@(),.-]|.?["'`]$)|@(?:[w-]+s(?:between|like|x?or|and|div)s*?[^ws]|w+s+(?:between|like|x?or|and|div)s*?["'`d]+)|["'`]s*?(?:between|like|x?or|and|div)s*?["'`]?d|[^ws:]s*?dW+[^ws]s*?["'`].|[^ws]w+s*?[|-]s*?["'`]s*?w|Winformation_schema|\\x(?:23|27|3d)|table_nameW))
      transformations:
        - t:none
        - t:urlDecodeUni
actions:
    - type: setvar
      key: tx.sql_injection_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-sqli
    - OWASP_CRS
    - capec/1000/152/248/66
    - PCI/6.5.2
    - paranoia-level/2
