id: "9006510"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: /posts/
conditions:
    - operator: '@rx'
      variable: REQUEST_URI
      value: /posts/d+/report$
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:message
chain: []
tags: []
