id: "959060"
msg: ""
severity: 0
phase: 4
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@ge'
      variable: TX:PARANOIA_LEVEL
      value: "1"
      transformations:
        - t:none
actions:
    - type: setvar
      key: tx.outbound_anomaly_score
      value: +%{tx.outbound_anomaly_score_pl1}
chain: []
tags: []
