id: "920500"
msg: Attempt to access a backup or working file
severity: 25
phase: 2
action: block
pre_filter_keyword: "~"
conditions:
    - operator: '@rx'
      variable: REQUEST_URI
      value: .[^.~]+~(?:/.*|)$
      transformations:
        - t:none
        - t:urlDecodeUni
actions:
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/210/272
    - PCI/6.5.10
