id: "9006000"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:crs_exclusions_xenforo|TX:crs_exclusions_xenforo'
      value: "0"
      transformations:
        - t:none
actions: []
chain: []
tags: []
