id: "921110"
msg: HTTP Request Smuggling Attack
severity: 25
phase: 2
action: block
pre_filter_keyword: options
conditions:
    - operator: '@rx'
      variable: ARGS_NAMES|ARGS|REQUEST_BODY|XML:/*
      value: (?:get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock)s+(?:/|w)[^s]*(?:s+http/d|[rn])
      transformations:
        - t:none
        - t:urlDecodeUni
        - t:htmlEntityDecode
        - t:lowercase
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.http_violation_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/210/272/220/33
