id: "910130"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:block_suspicious_ip'
      value: "0"
      transformations:
        - t:none
actions: []
chain:
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@eq'
          variable: '&TX:block_harvester_ip'
          value: "0"
          transformations: []
      actions: []
      chain: []
      tags: []
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@eq'
          variable: '&TX:block_spammer_ip'
          value: "0"
          transformations: []
      actions: []
      chain: []
      tags: []
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@eq'
          variable: '&TX:block_search_ip'
          value: "0"
          transformations: []
      actions: []
      chain: []
      tags: []
tags:
    - OWASP_CRS
