id: "913110"
msg: Found request header associated with security scanner
severity: 25
phase: 2
action: block
pre_filter_keyword: bytes=0-,5-0,5-1,5-2,5-3,5-4,5-5,5-6,5-7,5-8,5-9,5-10,5-11,5-12,5-13,5-14
conditions:
    - operator: '@pm'
      variable: REQUEST_HEADERS_NAMES|REQUEST_HEADERS
      value: acunetix-product (acunetix web vulnerability scanner acunetix-scanning-agreement acunetix-user-agreement myvar=1234 x-ratproxy-loop bytes=0-,5-0,5-1,5-2,5-3,5-4,5-5,5-6,5-7,5-8,5-9,5-10,5-11,5-12,5-13,5-14 x-scanner
      transformations:
        - t:none
        - t:lowercase
actions:
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: ip.reput_block_flag
      value: "1"
    - type: setvar
      key: ip.reput_block_reason
      value: '%{rule.msg}'
    - type: expirevar
      key: ip.reput_block_flag
      value: '%{tx.reput_block_duration}'
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-reputation-scanner
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/118/224/541/310
    - PCI/6.5.10
