id: "912130"
msg: ""
severity: 10
phase: 1
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: IP:DOS_BLOCK
      value: "1"
      transformations:
        - t:none
actions:
    - type: setvar
      key: ip.dos_block_counter
      value: "+1"
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-dos
    - OWASP_CRS
    - capec/1000/210/227/469
