id: "901164"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:restricted_extensions'
      value: "0"
      transformations: []
actions:
    - type: setvar
      key: tx.restricted_extensions
      value: .asa/ .asax/ .ascx/ .axd/ .backup/ .bak/ .bat/ .cdx/ .cer/ .cfg/ .cmd/ .com/ .config/ .conf/ .cs/ .csproj/ .csr/ .dat/ .db/ .dbf/ .dll/ .dos/ .htr/ .htw/ .ida/ .idc/ .idq/ .inc/ .ini/ .key/ .licx/ .lnk/ .log/ .mdb/ .old/ .pass/ .pdb/ .pol/ .printer/ .pwd/ .rdb/ .resources/ .resx/ .sql/ .swp/ .sys/ .vb/ .vbs/ .vbproj/ .vsdisco/ .webinfo/ .xsd/ .xsx/
chain: []
tags: []
