id: "941330"
msg: IE XSS Filters - Attack Detected
severity: 25
phase: 2
action: block
pre_filter_keyword: \u006c
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: (?i:["'][ ]*(?:[^a-z0-9~_:' ]|in).*?(?:(?:l|\\u006C)(?:o|\\u006F)(?:c|\\u0063)(?:a|\\u0061)(?:t|\\u0074)(?:i|\\u0069)(?:o|\\u006F)(?:n|\\u006E)|(?:n|\\u006E)(?:a|\\u0061)(?:m|\\u006D)(?:e|\\u0065)|(?:o|\\u006F)(?:n|\\u006E)(?:e|\\u0065)(?:r|\\u0072)(?:r|\\u0072)(?:o|\\u006F)(?:r|\\u0072)|(?:v|\\u0076)(?:a|\\u0061)(?:l|\\u006C)(?:u|\\u0075)(?:e|\\u0065)(?:O|\\u004F)(?:f|\\u0066)).*?=)
      transformations:
        - t:none
        - t:urlDecodeUni
        - t:htmlEntityDecode
        - t:compressWhitespace
actions:
    - type: setvar
      key: tx.xss_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-xss
    - OWASP_CRS
    - capec/1000/152/242
    - PCI/6.5.1
    - paranoia-level/2
