id: "931100"
msg: 'Possible Remote File Inclusion (RFI) Attack: URL Parameter using IP Address'
severity: 25
phase: 2
action: block
pre_filter_keyword: http
conditions:
    - operator: '@rx'
      variable: ARGS
      value: ^(?i:file|ftps?|https?)://(?:d{1,3}.d{1,3}.d{1,3}.d{1,3})
      transformations:
        - t:none
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.rfi_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-rfi
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/152/175/253
