id: "901170"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:monitor_anomaly_score'
      value: "0"
      transformations: []
actions:
    - type: setvar
      key: tx.monitor_anomaly_score
      value: "0"
chain: []
tags: []
