id: "9006240"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: misc/find-emoji&q=
conditions:
    - operator: '@rx'
      variable: REQUEST_URI
      value: /index.php?misc/find-emoji&q=
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetById
      value: 921151;ARGS:q
chain: []
tags: []
