id: "942101"
msg: SQL Injection Attack Detected via libinjection
severity: 25
phase: 2
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@detectSQLi'
      variable: REQUEST_BASENAME
      value: ""
      transformations:
        - t:none
        - t:utf8toUnicode
        - t:urlDecodeUni
        - t:removeNulls
actions:
    - type: setvar
      key: tx.sql_injection_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl3
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-sqli
    - OWASP_CRS
    - capec/1000/152/248/66
    - PCI/6.5.2
    - paranoia-level/3
