id: "942420"
msg: 'Restricted SQL Character Anomaly Detection (cookies): # of special characters exceeded (8)'
severity: 10
phase: 2
action: block
pre_filter_keyword: :;"'´’‘`<>
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES
      value: ((?:[~!@#$%^&*()-+={}[]|:;"'´’‘`<>][^~!@#$%^&*()-+={}[]|:;"'´’‘`<>]*?){8})
      transformations:
        - t:none
        - t:urlDecodeUni
actions:
    - type: setvar
      key: tx.anomaly_score_pl3
      value: +%{tx.warning_anomaly_score}
    - type: setvar
      key: tx.sql_injection_score
      value: +%{tx.warning_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-sqli
    - OWASP_CRS
    - capec/1000/152/248/66
    - PCI/6.5.2
    - paranoia-level/3
