id: "901160"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:allowed_methods'
      value: "0"
      transformations: []
actions:
    - type: setvar
      key: tx.allowed_methods
      value: GET HEAD POST OPTIONS
chain: []
tags: []
