id: "901440"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: "0"
conditions:
    - operator: '@rx'
      variable: TX:sampling_rnd100
      value: ^0([0-9])
      transformations: []
actions:
    - type: setvar
      key: TX.sampling_rnd100
      value: '%{TX.1}'
chain: []
tags: []
