id: "921151"
msg: HTTP Header Injection Attack via payload (CR/LF detected)
severity: 25
phase: 2
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@rx'
      variable: ARGS
      value: '[nr]'
      transformations:
        - t:none
        - t:urlDecodeUni
        - t:htmlEntityDecode
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.http_violation_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/2
    - OWASP_CRS
    - capec/1000/210/272/220/33
