id: "9002143"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /index.php
      transformations:
        - t:none
actions: []
chain:
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@eq'
          variable: '&ARGS:rest_route'
          value: "1"
          transformations:
            - t:none
      actions: []
      chain: []
      tags: []
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: /media
      conditions:
        - operator: '@rx'
          variable: ARGS:rest_route
          value: ^/wp/v[0-9]+/media
          transformations:
            - t:none
      actions:
        - type: ctl
          key: ruleRemoveById
          value: "200002"
        - type: ctl
          key: ruleRemoveById
          value: "200003"
      chain: []
      tags: []
tags: []
