id: "920410"
msg: Total uploaded files size too large
severity: 25
phase: 2
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&TX:COMBINED_FILE_SIZES'
      value: "1"
      transformations:
        - t:none
actions: []
chain:
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@gt'
          variable: FILES_COMBINED_SIZE
          value: '%{tx.combined_file_sizes}'
          transformations:
            - t:none
      actions:
        - type: setvar
          key: tx.anomaly_score_pl1
          value: +%{tx.critical_anomaly_score}
      chain: []
      tags: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/210/272
