id: "9006230"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /index.php?editor/media
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetById
      value: 931130;ARGS:url
    - type: ctl
      key: ruleRemoveTargetById
      value: 942130;ARGS:url
chain: []
tags: []
