id: "9006200"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /index.php?editor/to-html
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:bb_code
    - type: ctl
      key: ruleRemoveTargetById
      value: 942200;ARGS:attachment_hash_combined
    - type: ctl
      key: ruleRemoveTargetById
      value: 942260;ARGS:attachment_hash_combined
    - type: ctl
      key: ruleRemoveTargetById
      value: 942340;ARGS:attachment_hash_combined
    - type: ctl
      key: ruleRemoveTargetById
      value: 942370;ARGS:attachment_hash_combined
chain: []
tags: []
