id: "920330"
msg: Empty User Agent Header
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@rx'
      variable: REQUEST_HEADERS:User-Agent
      value: ^$
      transformations:
        - t:none
actions:
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.notice_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/210/272
