id: "942390"
msg: SQL Injection Attack
severity: 25
phase: 2
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: (?:b(?:(?i:xor)bs+(?:'[^=]{1,10}'(?:s*?[=<>])?|d{1,10}(?:s*?[=<>])?)|(?i:or)bs+(?:'[^=]{1,10}'(?:s*?[=<>])?|d{1,10}(?:s*?[=<>])?))|(?i:borb ?['"][^=]{1,10}['"] ?[=<>]+)|(?i:'s+xors+.{1,20}[+-!<>=])|(?i:'s+ors+.{1,20}[+-!<>=])|(?i:borb ?d{1,10} ?[=<>]+))
      transformations:
        - t:none
        - t:urlDecodeUni
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.sql_injection_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-sqli
    - OWASP_CRS
    - capec/1000/152/248/66
    - PCI/6.5.2
    - paranoia-level/2
