id: "920320"
msg: Missing User Agent Header
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@eq'
      variable: '&REQUEST_HEADERS:User-Agent'
      value: "0"
      transformations:
        - t:none
actions:
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.notice_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - OWASP_CRS
    - capec/1000/210/272
    - PCI/6.5.10
    - paranoia-level/2
