id: "942510"
msg: SQLi bypass attempt by ticks or backticks detected
severity: 25
phase: 2
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@rx'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: (?:`((?:[ws=_-+{}()<@]){2,29}|(?:[A-Za-z0-9+/]{4})+(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?)`)
      transformations:
        - t:none
        - t:urlDecodeUni
actions:
    - type: setvar
      key: tx.sql_injection_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl2
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-sqli
    - OWASP_CRS
    - capec/1000/152/248/66
    - PCI/6.5.2
    - paranoia-level/2
