id: "949017"
msg: ""
severity: 0
phase: 1
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@lt'
      variable: TX:EXECUTING_PARANOIA_LEVEL
      value: "4"
      transformations: []
actions: []
chain: []
tags: []
