id: "9003150"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: /index.php/core/preview.png
conditions:
    - operator: '@contains'
      variable: REQUEST_URI
      value: /index.php/core/preview.png
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetById
      value: 932150;ARGS:file
chain: []
tags: []
