id: "9002720"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /wp-admin/nav-menus.php
      transformations:
        - t:none
actions: []
chain:
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: update
      conditions:
        - operator: '@streq'
          variable: ARGS:action
          value: update
          transformations:
            - t:none
      actions: []
      chain: []
      tags: []
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@eq'
          variable: '&ARGS:action'
          value: "1"
          transformations:
            - t:none
      actions:
        - type: ctl
          key: ruleRemoveTargetById
          value: 942460;ARGS:menu-name
        - type: ctl
          key: ruleRemoveTargetById
          value: 941330;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 941340;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942200;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942260;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942330;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942340;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942430;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942431;ARGS:nav-menu-data
        - type: ctl
          key: ruleRemoveTargetById
          value: 942460;ARGS:nav-menu-data
      chain: []
      tags: []
tags: []
