id: "941180"
msg: Node-Validator Blacklist Keywords
severity: 25
phase: 2
action: block
pre_filter_keyword: document.cookie
conditions:
    - operator: '@pm'
      variable: REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*
      value: document.cookie document.write .parentnode .innerhtml window.location -moz-binding <!-- --> <![cdata[
      transformations:
        - t:none
        - t:utf8toUnicode
        - t:urlDecodeUni
        - t:htmlEntityDecode
        - t:jsDecode
        - t:cssDecode
        - t:lowercase
        - t:removeNulls
actions:
    - type: ctl
      key: auditLogParts
      value: +E
    - type: setvar
      key: tx.xss_score
      value: +%{tx.critical_anomaly_score}
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-xss
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/152/242
