id: "9006700"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '@endsWith'
      variable: REQUEST_URI
      value: /index.php?dbtech-security/fingerprint
      transformations:
        - t:none
actions:
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:components[14][value]
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:components[15][value]
    - type: ctl
      key: ruleRemoveTargetByTag
      value: OWASP_CRS;ARGS:components[16][value]
chain: []
tags: []
