id: "9004310"
msg: ""
severity: 0
phase: 2
action: allow
pre_filter_keyword: ""
conditions:
    - operator: '!@streq'
      variable: ARGS:do
      value: admin
      transformations:
        - t:none
actions: []
chain: []
tags: []
