id: "921230"
msg: HTTP Range Header detected
severity: 25
phase: 1
action: block
pre_filter_keyword: ""
conditions:
    - operator: '@gt'
      variable: '&REQUEST_HEADERS:Range'
      value: "0"
      transformations:
        - t:none
actions:
    - type: setvar
      key: tx.anomaly_score_pl3
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/3
    - OWASP_CRS
    - capec/1000/210/272/220
