id: "921421"
msg: 'Content-Type header: Dangerous content type outside the mime type declaration'
severity: 25
phase: 1
action: block
pre_filter_keyword: application/
conditions:
    - operator: '@rx'
      variable: REQUEST_HEADERS:Content-Type
      value: ^[^;s,]+[;s,].*?(?:(?:application(?:/soap+|/)|text/)xml|application/(?:.+[+])?json)
      transformations:
        - t:none
        - t:lowercase
actions:
    - type: setvar
      key: tx.anomaly_score_pl1
      value: +%{tx.critical_anomaly_score}
chain: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/255/153
    - PCI/12.1
