id: "920240"
msg: URL Encoding Abuse Attack Attempt
severity: 10
phase: 2
action: block
pre_filter_keyword: application/x-www-form-urlencoded
conditions:
    - operator: '@rx'
      variable: REQUEST_HEADERS:Content-Type
      value: ^(?i)application/x-www-form-urlencoded
      transformations:
        - t:none
actions: []
chain:
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: x25
      conditions:
        - operator: '@rx'
          variable: REQUEST_BODY
          value: x25
          transformations: []
      actions: []
      chain: []
      tags: []
    - id: ""
      msg: ""
      severity: 10
      phase: 2
      action: block
      pre_filter_keyword: ""
      conditions:
        - operator: '@validateUrlEncoding'
          variable: REQUEST_BODY
          value: ""
          transformations: []
      actions:
        - type: setvar
          key: tx.anomaly_score_pl1
          value: +%{tx.warning_anomaly_score}
      chain: []
      tags: []
tags:
    - application-multi
    - language-multi
    - platform-multi
    - attack-protocol
    - paranoia-level/1
    - OWASP_CRS
    - capec/1000/255/153/267/72
